<a href="https://colab.research.google.com/github/felipequinto/estudos_python/blob/main/exercicios_estrutura_repeticao_condicional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estruturas de repetição e condicional

1. Imprima uma sequência de 25 números consecutivos.

In [ ]:
contador = 1
while contador <=25:
  print(contador)
  contador +=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [ ]:
for i in range(25):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


2. Imprima a sequência acima 2 vezes. Dica: for dentro de for ou while dentro de while, etc...

In [ ]:
for n in range(2):
  for i in range(25):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


3. Na sequência de 0 a 30, imprima somente os números pares. Dica: operador para pegar o resto de uma divisão: %

In [ ]:
for i in range(31):
  if i % 2 == 0:
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30


4. Mega Sena: 6 números entre 1 e 60 (1 sorteio). (usando uma estrutura de repetição e sem usar estruturas de repetição).
Dica: função np.random.randint

In [ ]:
# Pode gerar números repetidos

import numpy as np

for i in range(6):
  print(np.random.randint(1,61))
  

17
34
22
47
2
20


In [ ]:
# Não gera números repetidos

numeros_sorteados =[]

while len(numeros_sorteados) <6:
  numero = np.random.randint(1,61)

  if numero not in numeros_sorteados:
     numeros_sorteados.append(numero)

print('Números sorteados: ', numeros_sorteados)     

Números sorteados:  [30, 31, 59, 1, 34, 7]


In [ ]:
np.random.randint(1,61, 6) # Pode gerar números repetidos

array([52, 25, 39, 28, 15, 24])

In [ ]:
np.random.choice(range(1,61), 6, False) # Não gera números repetidos

array([24, 39, 11, 45,  1, 36])

5. Simule o resultado de um dado de 6 faces jogado 7 vezes. (usando uma estrutura de repetição e sem usar estruturas de
repetição). Dica: função np.random.randint

In [ ]:
for dado in range(7):
  print(np.random.randint(1,7))

6
3
3
5
3
6
2


In [ ]:
np.random.randint(1,7,7)

array([6, 1, 3, 6, 1, 1, 2])

6. Sabendo que o fatorial de um número é definido como:

   x! = x.(x-1).(x-2)...1

   Crie um script que calcule o fatorial de um número qualquer.


In [ ]:
num = 5

fat = 1

for i in range(1, num + 1):
  fat *= i

fat  

120

7. LEI DOS GRANDES NÚMEROS Teste a lei dos grandes números para N números aleatórios gerados com distribuição normal (média = 0 e desvio padrão = 1). Crie um script que conte quantos esses números caem entre -1 e 1 e divida por N. Você sabe que E(X) = 68.2% Verifique que a média(Xn) tende a E(X) conforme você roda o script para valores maiores de N

In [ ]:
experimentos = 1000
cont = 0

for i in range(experimentos):
  x = np.random.normal(size=1)
  if x > -1 and x < 1:
    cont +=1
cont / experimentos    

0.699